version: '2'
services:
  web:
    build: .
    ports:
      - "8000:80"
    volumes:
      - "./:/usr/src/app"
    links:
      - middleware
  middleware:
    image: rmohr/activemq:latest
    ports:
      - 61613
    volumes:
      - './middleware/activemq.xml:/opt/activemq/conf/activemq.xml'
  server:
    build: mcollective
    links:
      - middleware

  node:
    image: quay.io/prometheus/node-exporter
    ports:
      - "9100:9100"
    volumes:
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/:/rootfs:ro"
    command: '-collector.procfs=/host/proc -collector.sysfs=/host/sys -collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)" collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus/:/etc/prometheus/
    command:
      - '-config.file=/etc/prometheus/prometheus.yml'
      - '-storage.local.path=/prometheus'
    ports:
      - 9090:9090
    links:
      - web

  grafana:
    image: grafana/grafana
    links:
      - prometheus
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false

